[workspace]

members = [
    "server"
]



[package]
name = "bevymaze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
image = "0.24.6"
imageproc = "0.23.0"
petgraph = "0.6.3"
rand = "0.8.5"
rusttype = "0.9.3"
bevy_terrain = { path = "bevy_terrain" }
