[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type=["lib"]
bench = false

[dependencies]
bevy = "0.11.0"
bytemuck = "1.13.1"
fixed = "1.23.1"
image = "0.24.6"
itertools = "0.11.0"
noise = "0.8.2"
qoi = "0.4.1"
